### ISSUE TITLE
NoClassDefFoundError at StifleDetectionController

### ISSUE THREAD

**Issue by MarcelTUC** [sopeco/DynamicSpotter-Extensions#50]
#### How to reproduce
- Eclipse with DynamicSpotter-Plugin
- create a new project, set up the DynamicSpotter configuration: "workload.experiment.duration: 60", "workload.maxusers: 100".
- As Instrumentation Satellite Adapter use the "DynamicInstrumentationClient"
- As Measurement Satellite Adapter use the "MeasurementClient"
- As workload I am using JMeter.

Start Dynamic Spotter and the exception occurs.
#### Exception

`org/lpe/common/utils/sql/SQLStringUtils
java.lang.NoClassDefFoundError: org/lpe/common/utils/sql/SQLStringUtils
    at org.spotter.ext.detection.stifle.StifleDetectionController.analyzeDatasets(StifleDetectionController.java:271)
    at org.spotter.ext.detection.stifle.StifleDetectionController.analyze(StifleDetectionController.java:88)
    at org.spotter.core.detection.AbstractDetectionController.analyzeProblem(AbstractDetectionController.java:133)
    at org.spotter.core.Spotter.startDiagnosis(Spotter.java:143)
    at org.spotter.service.SpotterServiceWrapper$1.run(SpotterServiceWrapper.java:126)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.lpe.common.utils.sql.SQLStringUtils
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 10 more`

**Comment by snowball77** [comment]
The issues reported here often seem related to inconsistent compile 
states. Are you sure you built LPE, AIM, Spotter and Extensions in this 
order using "mvn clean install" per project? Does not seem so...

Also ensure, that each of the four projects is in the "without-i43-server" branch before you compile clean.

Am 26.10.15 um 14:42 schrieb MarcelTUC:

> ```
>     How to reproduce
> ```
> - Eclipse with DynamicSpotter-Plugin
> - create a new project, set up the DynamicSpotter configuration:
>   "workload.experiment.duration: 60", "workload.maxusers: 100".
> - As Instrumentation Satellite Adapter use the
>   "DynamicInstrumentationClient"
> - As Measurement Satellite Adapter use the "MeasurementClient"
> - As workload I am using JMeter.
> 
> Start Dynamic Spotter and the exception occurs.
> 
> ```
>     Exception
> ```
> 
> |org/lpe/common/utils/sql/SQLStringUtils
> java.lang.NoClassDefFoundError: org/lpe/common/utils/sql/SQLStringUtils
> at
> org.spotter.ext.detection.stifle.StifleDetectionController.analyzeDatasets(StifleDetectionController.java:271)
> at
> org.spotter.ext.detection.stifle.StifleDetectionController.analyze(StifleDetectionController.java:88)
> at
> org.spotter.core.detection.AbstractDetectionController.analyzeProblem(AbstractDetectionController.java:133)
> at org.spotter.core.Spotter.startDiagnosis(Spotter.java:143)
> at
> org.spotter.service.SpotterServiceWrapper$1.run(SpotterServiceWrapper.java:126)
> at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> at java.util.concurrent.FutureTask.run(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.ClassNotFoundException:
> org.lpe.common.utils.sql.SQLStringUtils
> at java.net.URLClassLoader$1.run(Unknown Source)
> at java.net.URLClassLoader$1.run(Unknown Source)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.net.URLClassLoader.findClass(Unknown Source)
> at java.lang.ClassLoader.loadClass(Unknown Source)
> at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
> at java.lang.ClassLoader.loadClass(Unknown Source)
> ... 10 more|
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sopeco/DynamicSpotter-Extensions/issues/50.

## 

Prof. Steffen Becker
Professur Softwaretechnik
Angewandte Informatik

Technische Universität Chemnitz
Straße der Nationen 62 | R. B216B
09111 Chemnitz
Germany

Tel:    +49 371 531-36144
Fax:    +49 371 531-836144

steffen.becker@informatik.tu-chemnitz.de
www.tu-chemnitz.de

**Comment by MarcelTUC** [comment]
All files are from the "without-i43-server" branch and I compiled them in the order you wrote.

**Comment by snowball77** [comment]
Very strange, something must have been gone wrong, the classes are there 
and I can also not reproduce this.

Am 26.10.15 um 14:58 schrieb MarcelTUC:

> All files are from the "without-i43-server" branch and i compiled them
> in the order you wrote.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sopeco/DynamicSpotter-Extensions/issues/50#issuecomment-151141670.

## 

Prof. Steffen Becker
Professur Softwaretechnik
Angewandte Informatik

Technische Universität Chemnitz
Straße der Nationen 62 | R. B216B
09111 Chemnitz
Germany

Tel:    +49 371 531-36144
Fax:    +49 371 531-836144

steffen.becker@informatik.tu-chemnitz.de
www.tu-chemnitz.de

**Comment by MarcelTUC** [comment]
I've downloaded the complete project again, and compiled after using this:
http://stackoverflow.com/questions/7408545/how-do-you-clear-apache-mavens-cache
So Maven compiled complete new but the error already occours.

**Comment by snowball77** [comment]
Could you try to check your LPE.jar using a unzip tool to see whether the missing classes are contained in it?

**Comment by MarcelTUC** [comment]
In the "org.lpe.common.utils.sql-1.0.4-SNAPSHOT.jar" there exists a "SQLStringUtils.class" so it should found?

**Comment by MarcelTUC** [comment]
Finally i found the problem.
I am starting the DS-Server out of Eclipse. After importing the complete projects as maven projects (AIM, LPE-Common, DS, DS-Extensions) I forgot to update the projects: right-click project -> maven -> update project.
Now this problem doesn't occur anymore.
